const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free shit',
      category: 'Shirt',
      image: '/images/shirt-1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'free shit',
      category: 'Shirt',
      image: '/images/shirt-2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 3,
      countInStock: 30,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'free shit',
      category: 'Shirt',
      image: '/images/shirt-3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'Pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
  ],
};

export default data;
