import Head from 'next/head';
import Image from 'next/image';

import React from 'react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app'></meta>
        <link rel='icon' href='/favicon.ico'></link>
      </Head>

      <h1 className='text-3xl font-bold'>Next Tailwind Amazona</h1>
    </div>
  );
}
